#!/bin/bash

echo "Loading AWS keys..."
source .env

echo "Building middleman site..."
bundle exec middleman build

echo "Pushing new files to S3..."
aws s3 sync build s3://manningpassingacademy.com --acl public-read --cache-control "public, max-age=86400"

